-- ============================================================
-- FORECAST LAYER - ML Sales Predictions
-- ============================================================
-- Purpose: Store sales forecasts generated by the forecasting
--          pipeline (forecasting_pipeline Airflow DAG).
--
-- Model: Per-category linear trend + 7-day rolling average
--        with payday and weekend multipliers.
--
-- Run this in pgAdmin against talastock_warehouse.
-- ============================================================

-- ── forecast_sales ────────────────────────────────────────────
-- One row per (forecast_date, category).
-- Stores predicted revenue + confidence interval.

CREATE TABLE IF NOT EXISTS analytics.forecast_sales (
    id                      SERIAL PRIMARY KEY,

    -- What we're forecasting
    forecast_date           DATE        NOT NULL,
    category                VARCHAR(100) NOT NULL,

    -- Predictions
    predicted_revenue       NUMERIC(12, 2) NOT NULL,
    predicted_units         INTEGER        NOT NULL,
    confidence_lower        NUMERIC(12, 2) NOT NULL,  -- 80% CI lower bound
    confidence_upper        NUMERIC(12, 2) NOT NULL,  -- 80% CI upper bound

    -- Model metadata
    model_version           VARCHAR(50)  NOT NULL DEFAULT 'linear_trend_v1',
    trained_on_days         INTEGER      NOT NULL,  -- how many historical days used
    mape                    NUMERIC(6, 3),          -- Mean Absolute Percentage Error
    rmse                    NUMERIC(12, 4),         -- Root Mean Squared Error

    -- Run metadata
    generated_at            TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    dag_run_id              VARCHAR(255),

    UNIQUE (forecast_date, category)
);

-- ── forecast_accuracy ─────────────────────────────────────────
-- Tracks how accurate past forecasts were once actuals arrive.
-- Populated by the forecasting_pipeline on each run.

CREATE TABLE IF NOT EXISTS analytics.forecast_accuracy (
    id                      SERIAL PRIMARY KEY,
    forecast_date           DATE         NOT NULL,
    category                VARCHAR(100) NOT NULL,
    predicted_revenue       NUMERIC(12, 2) NOT NULL,
    actual_revenue          NUMERIC(12, 2) NOT NULL,
    absolute_error          NUMERIC(12, 2) GENERATED ALWAYS AS
                                (ABS(actual_revenue - predicted_revenue)) STORED,
    pct_error               NUMERIC(8, 4) GENERATED ALWAYS AS (
                                CASE WHEN actual_revenue > 0
                                     THEN ABS(actual_revenue - predicted_revenue)
                                          / actual_revenue * 100
                                     ELSE NULL END
                            ) STORED,
    evaluated_at            TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    UNIQUE (forecast_date, category)
);

-- ── Indexes ───────────────────────────────────────────────────

CREATE INDEX IF NOT EXISTS idx_forecast_sales_date
    ON analytics.forecast_sales(forecast_date);

CREATE INDEX IF NOT EXISTS idx_forecast_sales_category
    ON analytics.forecast_sales(category);

CREATE INDEX IF NOT EXISTS idx_forecast_sales_date_cat
    ON analytics.forecast_sales(forecast_date, category);

CREATE INDEX IF NOT EXISTS idx_forecast_accuracy_date
    ON analytics.forecast_accuracy(forecast_date);

-- ── Comments ──────────────────────────────────────────────────

COMMENT ON TABLE analytics.forecast_sales IS
    '30-day revenue forecasts per category, generated by forecasting_pipeline DAG';

COMMENT ON TABLE analytics.forecast_accuracy IS
    'Retrospective accuracy tracking: predicted vs actual revenue per category/date';
